# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/hysteria/account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproxy/hysteria/account.proto\x12\x1bxray.proxy.hysteria.account\"\x17\n\x07\x41\x63\x63ount\x12\x0c\n\x04\x61uth\x18\x01 \x01(\tBs\n\x1f\x63om.xray.proxy.hysteria.accountP\x01Z0github.com/xtls/xray-core/proxy/hysteria/account\xaa\x02\x1bXray.Proxy.Hysteria.Accountb\x06proto3')



_ACCOUNT = DESCRIPTOR.message_types_by_name['Account']
Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNT,
  '__module__' : 'proxy.hysteria.account_pb2'
  # @@protoc_insertion_point(class_scope:xray.proxy.hysteria.account.Account)
  })
_sym_db.RegisterMessage(Account)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037com.xray.proxy.hysteria.accountP\001Z0github.com/xtls/xray-core/proxy/hysteria/account\252\002\033Xray.Proxy.Hysteria.Account'
  _ACCOUNT._serialized_start=61
  _ACCOUNT._serialized_end=84
# @@protoc_insertion_point(module_scope)
